/**
 * Casa dos Botões - Catálogo de produtos
 * ------------------------------------------------------------------
 * ATUALIZADO AUTOMATICAMENTE a partir do Google Doc da loja.
 * Para atualizar: rode `python3 scripts/extract_products.py` (em modo dev).
 *
 * Para ADICIONAR produtos: edite o Google Doc e atualize este arquivo.
 * Para REMOVER: apague o bloco.
 *
 * Campos:
 *   id          - identificador único (não pode repetir)
 *   nome        - nome exibido no card
 *   categoria   - uma das categorias em CDB_CATEGORIES
 *   preco       - valor numérico (ex: 20.00)
 *   unidade     - "pacote com 6", "pacote com 12", "unidade", etc.
 *   quantidade  - nº de unidades dentro de 1 pacote
 *   descricao   - texto curto exibido no card e na modal
 *   detalhes    - lista de bullets exibidos na modal
 *   images      - lista de nomes de arquivo .webp em images/products/
 *                 (suporta 1 ou mais fotos - sistema de galeria dinâmica)
 *   image       - primeira imagem (para fallback/compatibilidade)
 *   dimensao    - dimensões do pacote para cálculo de frete
 */

window.CDB_CATEGORIES = [
  { id: "plastico",    nome: "Botões de Plástico",    icone: "●", descricao: "Cores e tamanhos variados" },
  { id: "acrilico",    nome: "Botões de Acrílico",    icone: "◍", descricao: "Foscos, brilhantes e dupla face" },
  { id: "metal",       nome: "Botões de Metal",       icone: "◈", descricao: "Dourados, prateados e envelhecidos" },
  { id: "madeira",     nome: "Botões de Madeira",     icone: "◐", descricao: "Rústicos e artesanais" },
  { id: "madreperola", nome: "Madrepérola",           icone: "◇", descricao: "Acabamento nobre" },
  { id: "infantis",    nome: "Infantis",              icone: "☺", descricao: "Botões divertidos e coloridos" },
  { id: "linhas",      nome: "Linhas",                icone: "〜", descricao: "Para costura e bordado" },
  { id: "aviamentos",  nome: "Aviamentos",            icone: "✕", descricao: "Zíperes, velcro, elásticos" },
  { id: "agulhas",     nome: "Agulhas",               icone: "↑", descricao: "Para máquinas e mãos" },
  { id: "kits",        nome: "Kits",                  icone: "▦", descricao: "Pacotes completos para projetos" },
];

window.CDB_PRODUCTS = [
  {
    id: "botao-de-acrilico-amarelo-claro-fosco-15mm",
    nome: "Botão De Acrílico - Amarelo Claro Fosco 15mm",
    categoria: "acrilico",
    preco: 1.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor amarelo claro fosco, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Amarelo Claro Fosco",
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 240 unidades",
    ],
    images: [
      "botao-de-acrilico-amarelo-claro-fosco-15mm-1.webp",
    ],
    image: "botao-de-acrilico-amarelo-claro-fosco-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-de-acrilico-areia-17mm",
    nome: "Botão De Acrílico - Areia 17mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor areia, tamanho 17mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Areia",
      "Tamanho: 17mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 82 unidades",
    ],
    images: [
      "botao-de-acrilico-areia-17mm-1.webp",
    ],
    image: "botao-de-acrilico-areia-17mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-de-acrilico-vermelho-fosco-14mm",
    nome: "Botão De  Acrílico - Vermelho Fosco 14mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor vermelho fosco, tamanho 14mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Vermelho Fosco",
      "Tamanho: 14mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 228 unidades",
    ],
    images: [
      "botao-de-acrilico-vermelho-fosco-14mm-1.webp",
    ],
    image: "botao-de-acrilico-vermelho-fosco-14mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-de-acrilico-vinho-fosco-14mm",
    nome: "Botão De Acrílico - Vinho Fosco 14mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor vinho fosco, tamanho 14mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Vinho Fosco",
      "Tamanho: 14mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 638 unidades",
    ],
    images: [
      "botao-de-acrilico-vinho-fosco-14mm-1.webp",
    ],
    image: "botao-de-acrilico-vinho-fosco-14mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-de-acrilico-roxo-azulado-15mm",
    nome: "Botão De Acrílico - Roxo Azulado 15mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor roxo azulado, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Roxo Azulado",
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 966 unidades",
    ],
    images: [
      "botao-de-acrilico-roxo-azulado-15mm-1.webp",
    ],
    image: "botao-de-acrilico-roxo-azulado-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-de-acrilico-furta-cor-11mm",
    nome: "Botão De Acrílico - Furta Cor 11mm",
    categoria: "acrilico",
    preco: 3.50,
    unidade: "pacote com 10 unidades",
    quantidade: 10,
    descricao: "Botão na cor furta cor, tamanho 11mm, vendido em pacote com 10 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Furta Cor",
      "Tamanho: 11mm",
      "Conteúdo: Pacote Com 10 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 762 unidades",
    ],
    images: [
      "botao-de-acrilico-furta-cor-11mm-1.webp",
    ],
    image: "botao-de-acrilico-furta-cor-11mm-1.webp",
    dimensao: { pesoG: 30, comprimentoCm: 12, larguraCm: 8, alturaCm: 1.5 },
  },
  {
    id: "botao-de-acrilico-rosa-bebe-fosco-17mm",
    nome: "Botão De Acrílico - Rosa Bebe Fosco 17mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor rosa bebe fosco, tamanho 17mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Rosa Bebe Fosco",
      "Tamanho: 17mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 494 unidades",
    ],
    images: [
      "botao-de-acrilico-rosa-bebe-fosco-17mm-1.webp",
    ],
    image: "botao-de-acrilico-rosa-bebe-fosco-17mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-de-acrilico-branco-mesclado-fosc-22mm",
    nome: "Botão De Acrílico - Branco Mesclado Fosco 22mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor branco mesclado fosco, tamanho 22mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Branco Mesclado Fosco",
      "Tamanho: 22mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 922 unidades",
    ],
    images: [
      "botao-de-acrilico-branco-mesclado-fosc-22mm-1.webp",
    ],
    image: "botao-de-acrilico-branco-mesclado-fosc-22mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-de-acrilico-preto-mesclado-brilh-20mm",
    nome: "Botão De Acrílico - Preto Mesclado Brilhante 20mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor preto mesclado brilhante, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Preto Mesclado Brilhante",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 965 unidades",
    ],
    images: [
      "botao-de-acrilico-preto-mesclado-brilh-20mm-1.webp",
    ],
    image: "botao-de-acrilico-preto-mesclado-brilh-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-de-acrilico-fosco-dupla-face-branco-bege-mesclado-15mm",
    nome: "Botão De Acrílico Fosco Dupla Face - Branco-Bege Mesclado Dupla Face 15mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor branco-bege mesclado dupla face, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Branco-Bege Mesclado Dupla Face",
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 1324 unidades",
    ],
    images: [
      "botao-de-acrilico-fosco-dupla-face-branco-bege-mesclado-15mm-1.webp",
      "botao-de-acrilico-fosco-dupla-face-branco-bege-mesclado-15mm-2.webp",
    ],
    image: "botao-de-acrilico-fosco-dupla-face-branco-bege-mesclado-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-acrilico-brilhante-marrom-areia-18mm",
    nome: "Botão Acrílico Brilhante - Marrom Areia 18mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor marrom areia, tamanho 18mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Marrom Areia",
      "Tamanho: 18mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-brilhante-marrom-areia-18mm-1.webp",
    ],
    image: "botao-acrilico-brilhante-marrom-areia-18mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-acrilico-fosco-preto-mesclado-25mm",
    nome: "Botão Acrílico Fosco - Preto Mesclado 25mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor preto mesclado, tamanho 25mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Preto Mesclado",
      "Tamanho: 25mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-fosco-preto-mesclado-25mm-1.webp",
    ],
    image: "botao-acrilico-fosco-preto-mesclado-25mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-acrilico-preto-preto-brilhante-17mm",
    nome: "Botao Acrilico Preto - Preto Brilhante 17mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor preto brilhante, tamanho 17mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Preto Brilhante",
      "Tamanho: 17mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-preto-preto-brilhante-17mm-1.webp",
    ],
    image: "botao-acrilico-preto-preto-brilhante-17mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-acrilico-branco-branco-17mm",
    nome: "Botão Acrílico Branco - Branco 17mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor branco, tamanho 17mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Branco",
      "Tamanho: 17mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-branco-branco-17mm-1.webp",
    ],
    image: "botao-acrilico-branco-branco-17mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-acrilico-fosco-marron-areia-20mm",
    nome: "Botão Acrílico Fosco - Marron Areia 20mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor marron areia, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Marron Areia",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 478 unidades",
    ],
    images: [
      "botao-acrilico-fosco-marron-areia-20mm-1.webp",
    ],
    image: "botao-acrilico-fosco-marron-areia-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-acrilico-brilhante-branco-furta-cor-15mm",
    nome: "Botão Acrílico Brilhante - Branco Furta Cor 15mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor branco furta cor, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Branco Furta Cor",
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 979 unidades",
    ],
    images: [
      "botao-acrilico-brilhante-branco-furta-cor-15mm-1.webp",
    ],
    image: "botao-acrilico-brilhante-branco-furta-cor-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-acrilico-brilhante-dupla-face-rajado-e-branco-20mm-hor",
    nome: "Botão Acrílico Brilhante Dupla Face - Rajado E Branco 20mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor rajado e branco, tamanho 20mm HORIZONTAL 16 MM VERTICAL, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Rajado E Branco",
      "Tamanho: 20mm HORIZONTAL 16 MM VERTICAL",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 167 unidades",
    ],
    images: [
      "botao-acrilico-brilhante-dupla-face-rajado-e-branco-20mm-hor-1.webp",
      "botao-acrilico-brilhante-dupla-face-rajado-e-branco-20mm-hor-2.webp",
    ],
    image: "botao-acrilico-brilhante-dupla-face-rajado-e-branco-20mm-hor-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-acrilico-fosco-bege-mesclado-com-ma-22mm",
    nome: "Botão Acrílico Fosco - Bege Mesclado Com Marrom Off White 22mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor bege mesclado com marrom off white, tamanho 22mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Bege Mesclado Com Marrom Off White",
      "Tamanho: 22mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-fosco-bege-mesclado-com-ma-22mm-1.webp",
    ],
    image: "botao-acrilico-fosco-bege-mesclado-com-ma-22mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-acrilico-fosco-mesclado-claro-20mm",
    nome: "Botão Acrílico Fosco - Mesclado Claro 20mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor mesclado claro, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Mesclado Claro",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-fosco-mesclado-claro-20mm-1.webp",
    ],
    image: "botao-acrilico-fosco-mesclado-claro-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-acrilico-brilhante-marrom-mesclado-20mm",
    nome: "Botão Acrílico Brilhante - Marrom Mesclado 20mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor marrom mesclado, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Marrom Mesclado",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 537 unidades",
    ],
    images: [
      "botao-acrilico-brilhante-marrom-mesclado-20mm-1.webp",
    ],
    image: "botao-acrilico-brilhante-marrom-mesclado-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-acrilico-fosco-marrom-mesclado-com-20mm",
    nome: "Botão Acrílico Fosco - Marrom Mesclado Com Veias 20mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor marrom mesclado com veias, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Marrom Mesclado Com Veias",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
    ],
    images: [
      "botao-acrilico-fosco-marrom-mesclado-com-20mm-1.webp",
    ],
    image: "botao-acrilico-fosco-marrom-mesclado-com-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-20mm",
    nome: "Botao Plastico - Dourado 20mm",
    categoria: "plastico",
    preco: 24.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 6 unidades",
    ],
    images: [
      "botao-plastico-dourado-20mm-1.webp",
      "botao-plastico-dourado-20mm-2.webp",
      "botao-plastico-dourado-20mm-3.webp",
    ],
    image: "botao-plastico-dourado-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-19mm",
    nome: "Botao Plastico - Dourado 19mm",
    categoria: "plastico",
    preco: 22.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 19mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 19mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 6 unidades",
    ],
    images: [
      "botao-plastico-dourado-19mm-1.webp",
      "botao-plastico-dourado-19mm-2.webp",
      "botao-plastico-dourado-19mm-3.webp",
    ],
    image: "botao-plastico-dourado-19mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-20mm",
    nome: "Botao Plastico - Dourado 20mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-20mm-1.webp",
      "botao-plastico-dourado-20mm-2.webp",
    ],
    image: "botao-plastico-dourado-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-madreperola-17mm",
    nome: "Botao Madreperola 17mm",
    categoria: "madreperola",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão artesanal, tamanho 17mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Tamanho: 17mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Madreperola",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-madreperola-17mm-1.webp",
      "botao-madreperola-17mm-2.webp",
    ],
    image: "botao-madreperola-17mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-plastico-dourado-18mm",
    nome: "Botao Plastico - Dourado 18mm",
    categoria: "plastico",
    preco: 16.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 18mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 18mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-18mm-1.webp",
      "botao-plastico-dourado-18mm-2.webp",
    ],
    image: "botao-plastico-dourado-18mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-plastico-durado-23mm",
    nome: "Botao Plastico - Durado 23mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor durado, tamanho 23mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Durado",
      "Tamanho: 23mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-durado-23mm-1.webp",
      "botao-plastico-durado-23mm-2.webp",
      "botao-plastico-durado-23mm-3.webp",
    ],
    image: "botao-plastico-durado-23mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-plastico-dourado-20mm",
    nome: "Botao Plastico - Dourado 20mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 6 unidades",
    ],
    images: [
      "botao-plastico-dourado-20mm-1.webp",
      "botao-plastico-dourado-20mm-2.webp",
      "botao-plastico-dourado-20mm-3.webp",
    ],
    image: "botao-plastico-dourado-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-20mm",
    nome: "Botao Plastico - Dourado 20mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 20mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 20mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-20mm-1.webp",
      "botao-plastico-dourado-20mm-2.webp",
    ],
    image: "botao-plastico-dourado-20mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-19mm",
    nome: "Botao Plastico - Dourado 19mm",
    categoria: "plastico",
    preco: 22.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 19mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 19mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 6 unidades",
    ],
    images: [
      "botao-plastico-dourado-19mm-1.webp",
      "botao-plastico-dourado-19mm-2.webp",
      "botao-plastico-dourado-19mm-3.webp",
    ],
    image: "botao-plastico-dourado-19mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-15mm",
    nome: "Botao Plastico - Dourado 15mm",
    categoria: "plastico",
    preco: 18.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-15mm-1.webp",
      "botao-plastico-dourado-15mm-2.webp",
      "botao-plastico-dourado-15mm-3.webp",
    ],
    image: "botao-plastico-dourado-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-plastico-15mm",
    nome: "Botao Plastico 15mm",
    categoria: "plastico",
    preco: 15.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão artesanal, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 18 unidades",
    ],
    images: [
      "botao-plastico-15mm-1.webp",
      "botao-plastico-15mm-2.webp",
    ],
    image: "botao-plastico-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-plastico-dourado-25mm",
    nome: "Botao Plastico - Dourado 25mm",
    categoria: "plastico",
    preco: 24.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 25mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 25mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-25mm-1.webp",
      "botao-plastico-dourado-25mm-2.webp",
      "botao-plastico-dourado-25mm-3.webp",
    ],
    image: "botao-plastico-dourado-25mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-acrilico-fosco-mesclado-25mm",
    nome: "Botão Acrílico Fosco - Mesclado 25mm",
    categoria: "acrilico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor mesclado, tamanho 25mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Mesclado",
      "Tamanho: 25mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Acrilico",
      "Estoque disponível: 460 unidades",
    ],
    images: [
      "botao-acrilico-fosco-mesclado-25mm-1.webp",
    ],
    image: "botao-acrilico-fosco-mesclado-25mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-plastico-preto-25mm",
    nome: "Botao Plastico - Preto 25mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor preto, tamanho 25mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Preto",
      "Tamanho: 25mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-preto-25mm-1.webp",
      "botao-plastico-preto-25mm-2.webp",
    ],
    image: "botao-plastico-preto-25mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-plastico-dourado-22mm",
    nome: "Botao Plastico - Dourado 22mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 22mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 22mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-22mm-1.webp",
      "botao-plastico-dourado-22mm-2.webp",
      "botao-plastico-dourado-22mm-3.webp",
    ],
    image: "botao-plastico-dourado-22mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-23mm",
    nome: "Botao Plastico - Dourado 23mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 23mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 23mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-23mm-1.webp",
      "botao-plastico-dourado-23mm-2.webp",
    ],
    image: "botao-plastico-dourado-23mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-plastico-dourado-25mm",
    nome: "Botao Plastico - Dourado 25mm",
    categoria: "plastico",
    preco: 24.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 25mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 25mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-25mm-1.webp",
      "botao-plastico-dourado-25mm-2.webp",
      "botao-plastico-dourado-25mm-3.webp",
    ],
    image: "botao-plastico-dourado-25mm-1.webp",
    dimensao: { pesoG: 90, comprimentoCm: 20, larguraCm: 14, alturaCm: 3 },
  },
  {
    id: "botao-plastico-dourado-22mm",
    nome: "Botao Plastico - Dourado 22mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 22mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 22mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-22mm-1.webp",
      "botao-plastico-dourado-22mm-2.webp",
      "botao-plastico-dourado-22mm-3.webp",
    ],
    image: "botao-plastico-dourado-22mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-de-plastico-preto-22mm",
    nome: "Botao De Plastico - Preto 22mm",
    categoria: "plastico",
    preco: 16.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor preto, tamanho 22mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Preto",
      "Tamanho: 22mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 6 unidades",
    ],
    images: [
      "botao-de-plastico-preto-22mm-1.webp",
      "botao-de-plastico-preto-22mm-2.webp",
    ],
    image: "botao-de-plastico-preto-22mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-15mm",
    nome: "Botao Plastico - Dourado 15mm",
    categoria: "plastico",
    preco: 18.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 15mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 15mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-15mm-1.webp",
      "botao-plastico-dourado-15mm-2.webp",
      "botao-plastico-dourado-15mm-3.webp",
    ],
    image: "botao-plastico-dourado-15mm-1.webp",
    dimensao: { pesoG: 50, comprimentoCm: 16, larguraCm: 11, alturaCm: 2 },
  },
  {
    id: "botao-plastico-dourado-21mm",
    nome: "Botao Plastico - Dourado 21mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 21mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 21mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-21mm-1.webp",
      "botao-plastico-dourado-21mm-2.webp",
    ],
    image: "botao-plastico-dourado-21mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
  {
    id: "botao-plastico-dourado-22mm",
    nome: "Botao Plastico - Dourado 22mm",
    categoria: "plastico",
    preco: 20.00,
    unidade: "pacote com 6 unidades",
    quantidade: 6,
    descricao: "Botão na cor dourado, tamanho 22mm, vendido em pacote com 6 unidades, para seus projetos de costura e artesanato.",
    detalhes: [
      "Cor: Dourado",
      "Tamanho: 22mm",
      "Conteúdo: Pacote Com 6 Unidades",
      "Categoria: Plastico",
      "Estoque disponível: 12 unidades",
    ],
    images: [
      "botao-plastico-dourado-22mm-1.webp",
      "botao-plastico-dourado-22mm-2.webp",
    ],
    image: "botao-plastico-dourado-22mm-1.webp",
    dimensao: { pesoG: 70, comprimentoCm: 18, larguraCm: 12, alturaCm: 2.5 },
  },
];
